site_name: damage
docs_dir: 'docs'
nav:
  - "Damage: file manifest tools": index.md
  - How to use the Damage application: how_to_use_gui_damage.md
#  - Building the Damage GUI application: building_damage_gui_app.md
  - How to use the Damage console utility: how_to_use_damage.md
#  - Building the Damage console utility: building_damage_binary.md
  - API reference: api_reference.md
  - Frequently asked questions: faq.md
  - Credits: credits.md

extra_css: [css/extra.css]

markdown_extensions:
  - smarty
  - toc:
      permalink: True
  - codehilite:
      guess_lang: False
      linenums: False
      use_pygments: False
  - attr_list

theme: readthedocs

plugins:
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            docstring_style: numpy
            show_source: true
            filters: public
  - search
